---
title: "Final lab"
author: "Leslie Huynh"
format: html
---
[Lien](https://github.com/leslie3001/battletech.git) du dossier github 

```{r}
#| message: false
#| echo: false
here::i_am("Huynh.qmd")
library(vroom)
library(ggplot2)
library(dplyr)
library(tidyr)
library(here)
```

## Data loading 
```{r}
#| message: false
#| echo: false
system <- vroom(here("systems.csv"))
```

```{r}
#| message: false
#| echo: false
dim(system)
```
Il y a bien le bon nombre d'observations et de variables attendues
```{r}
#| message: false
#| echo: false
str(system)
```
Toutes les données numériques sont à leur bon format.


```{r}
#| message: false
#| echo: false
valeurs_manquantes <- colSums(is.na(system))
knitr::kable(valeurs_manquantes, caption = "Valeurs manquantes")
```

```{r}
#| message: false
#| echo: false
nb_obs <- nrow(system)
nb_var <- ncol(system)
valeur_manquante1 <- sum(rowSums(is.na(system)) > 0)

tableau <- data.frame(
  Nombre_lignes = nb_obs,
  Nombre_colonnes = nb_var,
  Valeurs_manquantes = valeurs_manquantes,
  Nombre_observations_avec_1_NA = valeur_manquante1)
  

knitr::kable(tableau, caption = "Description")

```
## Analyse
```{r}
#| message: false
#| echo: false
system |> 
  ggplot(aes(x=`star luminosity`, y=`Star Radius`))+
  geom_jitter(alpha = 0.5, na.rm = TRUE)+
  labs(title = "Radiation en fonction de la luminosité",
       x= "luminosité",
       y="radiation")
```
## Faction
```{r}
#| message: false
#| echo: false
faction <- vroom(here("the%factions.csv"))
controlling <- vroom(here("SYTEM%FACTION.csv"))
```


```{r}
#| message: false
#| echo: false
control_faction <- inner_join(controlling, faction, by="faction_key")
```


```{r}
#| message: false
#| echo: false
subset3063 <- control_faction |>
  filter(faction_key %in% c('A', 'I', 'U'))
```

```{r}
#| message: false
#| echo: false
subset3063 |> group_by(faction_key) |> summarise(n=n()) |> knitr::kable(caption="Nombre de systemes abandonné, independant et non découvert")
```

```{r}
#| message: false
#| echo: false
unmatched <- anti_join(faction, controlling, by = "faction_key") |> summarise(n=n())
knitr::kable(unmatched, caption="nombre de faction non trouvée dans system%faction")
```

```{r}
#| message: false
#| echo: false
control_faction |> ggplot(aes(x=`Faction Name`)) + geom_bar()+coord_flip()+
  labs(title="Nombre de systèmes controllés par les factions")
```

```{r}
#| message: false
#| echo: false
real_faction <- control_faction |>
  filter(!faction_key %in% c('A', 'I', 'U'))
```

```{r}
#| message: false
#| echo: false
system_faction <- inner_join(real_faction, system, by="STAR_NUMBER")
```

```{r}
#| message: false
#| echo: false
system_faction |> ggplot(aes(y=`Distance From The Sun`, x=`Faction Name`))+
  geom_boxplot()+ coord_flip()+
  labs(title="Distance au soleil selon les factions", 
       x="distance au soleil",
       y="Factions")
```
```{r}
#| message: false
#| echo: false
luminous <- system_faction |> select(`Faction Name`, `star luminosity`, Star)
```

```{r}
#| message: false
#| echo: false
luminous |> group_by(`Faction Name`) |> slice_max(`star luminosity`) |>
knitr::kable(luminous, caption="most luminous star for each station")
```





